version: "3.7"
services:

  redis:
    image: redis:alpine

  postgres:
    build: ./database
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PLANTGROWER_POSTGRES_PASSWORD_FILE=/run/secrets/plantgrower_postgres_password
    volumes:
      - plantgrower-volume:/var/lib/postgresql/data
    secrets:
      - postgres_password
      - plantgrower_postgres_password
      - postgres_db

  rabbitmq:
    image: rabbitmq:alpine

  django-migrations:
    image: eggmancw/plant_grower:latest
    command: ["migrate"]
    build:
      context: ./django-plantgrower
      dockerfile: Dockerfile.amd64
    environment:
      - PYTHONBUFFERED=0
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=plantgrower
      - POSTGRES_PASSWORD_FILE=/run/secrets/plantgrower_postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    depends_on:
      - postgres
    secrets:
      - postgres_db
      - plantgrower_postgres_password

  plantgrower:
    image: eggmancw/plant_grower:latest
    build:
      context: ./django-plantgrower
      dockerfile: Dockerfile.amd64
    ports:
      - "8000:8000"
    environment:
      - PYTHONBUFFERED=0
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=plantgrower
      - POSTGRES_PASSWORD_FILE=/run/secrets/plantgrower_postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    depends_on:
      - django-migrations
    secrets:
      - postgres_db
      - plantgrower_postgres_password

  # celery-worker:
  #   image: eggmancw/plant_grower:latest
  #   command: celery -A plant_grower worker -l info

  # celery-beat:
  #   image: eggmancw/plant_grower:latest
  #   command: celery -A plant_grower beat -l info
  #   depends_on:
  #     - django-migrations

secrets:
  postgres_password:
    file: ~/docker_secrets/postgres_password
  plantgrower_postgres_password:
    file: ~/docker_secrets/plantgrower_postgres_password
  postgres_db:
    file: ~/docker_secrets/postgres_db

volumes:
  plantgrower-volume:
